name: WolfSK2
description: Addon for Skript
version: 2.13.7.3
website: https://fmp.xaa.pl/ftp_server/EVOX_Interactive/WolfSk2/
main: pl.ajonx.wolfsk2.WolfSk2
depend: [Skript]
authors:
    - GempXPlay

commands:
    wolfsk:
        description: use '/wolfsk' for help
        aliases: [wsk, wolfskript, wolfsk]
        permission: wolfsk.*
        usage: /wolfsk